### ISSUE TITLE
IntelliJ stops supporting spring assistant Plugin  After updating it

### ISSUE THREAD

**Issue by CodeWithAdarsha** [1tontech/intellij-spring-assistant#29]
![image](https://user-images.githubusercontent.com/11813559/124624790-d5e7cc00-de9a-11eb-8e7e-b4e1019a550e.png)

**Comment by eltonsandre** [comment]
https://github.com/eltonsandre/intellij-spring-assistant/releases/tag/1.2.0 [fix+new features]

https://plugins.jetbrains.com/plugin/18622-spring-initializr-and-assistant
