### ISSUE TITLE
Doesn't Create additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by Bwvolleyball** [1tontech/intellij-spring-assistant#5]
This plugin will not create this file if it doesn't exist (even though it gives the prompt), and then it also doesn't read properties from this file if it does exist.

It only reads from `spring-configuration-metadata.json`.  It ideally should at a minimum read from both that file and a `additional-spring-configuration-metadata.json`

**Comment by prog110** [comment]
Please have a look https://github.com/1tontech/intellij-spring-assistant/tree/master/samples

The project already includes everything that is mentioned in the documentation

It does read from `additional-spring-configuration-metadata.json`

https://github.com/1tontech/intellij-spring-assistant/blob/master/samples/gradle/single-project/src/main/resources/META-INF/additional-spring-configuration-metadata.json
